# Generated by Django 5.2.17 on 2026-09-26 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('factory_name', models.CharField(max_length=255)),
                ('worker_username', models.CharField(max_length=150)),
                ('xrf_data', models.TextField()),
                ('final_recipe', models.TextField(blank=True, null=True)),
                ('final_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING_REVIEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDebateTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('chemist_proposal', models.TextField()),
                ('peer_critique', models.TextField()),
                ('auditor_critique', models.TextField()),
                ('safety_score', models.IntegerField()),
                ('hazards', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_turns', to='engine.batchrun')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('worker', 'Factory Floor Worker'), ('safety_officer', 'Safety Officer')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
